version: ’3.9 ’
services:
  pg-catalogo:
  image: postgres :16-alpine
  container_name: pg_catalogo
environment:
  POSTGRES_DB: SVC_catalogo
  POSTGRES_USER: SVC
  POSTGRES_PASSWORD: svc123
ports:
- " 5432:5432 "
volumes:
- pg_catalogo_data:/var/lib/postgresql/data
- ./sql/init_catalogo.sql:/docker-entrypoint-initdb.d/init.sql
networks:
- catalogo_net

pg-pedidos:
  image: postgres:16-alpine
  container_name: pg_pedidos
  environment:
    POSTGRES_DB: SVC_pedidos
    POSTGRES_USER: SVC
    POSTGRES_PASSWORD: svc123
  ports:
    - "5433:5432"
  volumes:
    - pg_pedidos_data:/var/lib/postgresql/data
    - ./sql/init_pedidos.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
    - catalogo_net


