spring.application.name=svc-catalogo
server.port=8001
server.servlet.context-path=/

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://pg-catalogo:5432/SVC_catalogo
spring.datasource.username=SVC
spring.datasource.password=svc123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=10

# Logging
logging.level.root=INFO
logging.level.uteq.aporte.catalogo=DEBUG
